In [41]:
import pandas as pd

In [42]:
marketing_customer_analysis_cleaned_lab6 = pd.read_csv('marketing_customer_analysis_cleaned_lab6.csv')

In [43]:
marketing_customer_analysis_cleaned_lab6 = marketing_customer_analysis_cleaned_lab6.drop('Unnamed: 0', axis=1) 

In [45]:
marketing_customer_analysis_cleaned_lab6 = marketing_customer_analysis_cleaned_lab6.drop('Effective To Date', axis=1) 

In [46]:
marketing_customer_analysis_cleaned_lab6.head()

Customer       State  Customer Lifetime Value  Coverage Education  \
0  DK49336     Arizona              4809.216960     Basic   College   
1  KX64629  California              2228.525238     Basic   College   
2  LZ68649  Washington             14947.917300     Basic  Bachelor   
3  XL78013      Oregon             22332.439460  Extended   College   
4  QA50777      Oregon              9025.067525   Premium  Bachelor   

  EmploymentStatus Gender  Income Location Code Marital Status  ...  \
0         Employed      M   48029      Suburban        Married  ...   
1       Unemployed      F       0      Suburban         Single  ...   
2         Employed      M   22139      Suburban         Single  ...   
3         Employed      M   49078      Suburban         Single  ...   
4    Medical Leave      F   23675      Suburban        Married  ...   

   Number of Open Complaints  Number of Policies     Policy Type  \
0                   0.000000                   9  Corporate Auto   
1                   0.000000                   1   Personal Auto   
2                   0.000000                   2   Personal Auto   
3                   0.000000                   2  Corporate Auto   
4                   0.384256                   7   Personal Auto   

         Policy  Renew Offer Type Sales Channel Total Claim Amount  \
0  Corporate L3            Offer3         Agent         292.800000   
1   Personal L3            Offer4   Call Center         744.924331   
2   Personal L3            Offer3   Call Center         480.000000   
3  Corporate L3            Offer2        Branch         484.013411   
4   Personal L2            Offer1        Branch         707.925645   

   Vehicle Class Vehicle Size  response Rate  
0  Four-Door Car      Medsize              0  
1  Four-Door Car      Medsize              0  
2            SUV      Medsize              0  
3  Four-Door Car      Medsize              1  
4  Four-Door Car      Medsize              0  

[5 rows x 23 columns]

In [ ]:
#encode categoricals

In [47]:
numerical = marketing_customer_analysis_cleaned_lab6.select_dtypes(include = ['int64', 'float64']) 
categoricals = marketing_customer_analysis_cleaned_lab6.select_dtypes(include = ['object'])

In [48]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder().fit(categoricals)
print(encoder.categories_)
encoded = encoder.transform(categoricals).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categoricals)
onehot_encoded.head()

[array(['AA10041', 'AA11235', 'AA16582', ..., 'ZZ89380', 'ZZ91716',
       'ZZ97035'], dtype=object), array(['Arizona', 'California', 'Nevada', 'Oregon', 'Washington'],
      dtype=object), array(['Basic', 'Extended', 'Premium'], dtype=object), array(['Bachelor', 'College', 'Doctor', 'High School or Below', 'Master'],
      dtype=object), array(['Disabled', 'Employed', 'Medical Leave', 'Retired', 'Unemployed'],
      dtype=object), array(['F', 'M'], dtype=object), array(['Rural', 'Suburban', 'Urban'], dtype=object), array(['Divorced', 'Married', 'Single'], dtype=object), array(['Corporate Auto', 'Personal Auto', 'Special Auto'], dtype=object), array(['Corporate L1', 'Corporate L2', 'Corporate L3', 'Personal L1',
       'Personal L2', 'Personal L3', 'Special L1', 'Special L2',
       'Special L3'], dtype=object), array(['Offer1', 'Offer2', 'Offer3', 'Offer4'], dtype=object), array(['Agent', 'Branch', 'Call Center', 'Web'], dtype=object), array(['Four-Door Car', 'Luxury Car', 'Luxury SUV

AttributeError: 'OneHotEncoder' object has no attribute 'categoricals'

In [49]:
categoricals.head(4)

Customer       State  Coverage Education EmploymentStatus Gender  \
0  DK49336     Arizona     Basic   College         Employed      M   
1  KX64629  California     Basic   College       Unemployed      F   
2  LZ68649  Washington     Basic  Bachelor         Employed      M   
3  XL78013      Oregon  Extended   College         Employed      M   

  Location Code Marital Status     Policy Type        Policy Renew Offer Type  \
0      Suburban        Married  Corporate Auto  Corporate L3           Offer3   
1      Suburban         Single   Personal Auto   Personal L3           Offer4   
2      Suburban         Single   Personal Auto   Personal L3           Offer3   
3      Suburban         Single  Corporate Auto  Corporate L3           Offer2   

  Sales Channel  Vehicle Class Vehicle Size  
0         Agent  Four-Door Car      Medsize  
1   Call Center  Four-Door Car      Medsize  
2   Call Center            SUV      Medsize  
3        Branch  Four-Door Car      Medsize

In [51]:
X_cat1=categoricals.drop(['Customer', 'State', 'EmploymentStatus', 'Education', 'Gender', 'Location Code', 'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Vehicle Class', 'Vehicle Size'],axis=1) 


In [54]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder().fit(X_cat1)
print(encoder.categories_)

[array(['Basic', 'Extended', 'Premium'], dtype=object)]


In [55]:
X_cat1.head()

Coverage
0     Basic
1     Basic
2     Basic
3  Extended
4   Premium

In [62]:
#assign variabele encoded to transform and convert to array
encoded= encoder.transform(X_cat1).toarray()
print (encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [66]:
# Create a dataframe with columns
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)
onehot_encoded.head()

Basic Extended Premium
0   1.0      0.0     0.0
1   1.0      0.0     0.0
2   1.0      0.0     0.0
3   0.0      1.0     0.0
4   0.0      0.0     1.0

In [59]:
X_cat2=categoricals.drop(['Customer', 'State', 'Coverage', 'Education', 'Gender', 'Location Code', 'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Vehicle Class', 'Vehicle Size'],axis=1) 
from sklearn.preprocessing import OneHotEncoder
encoder2 = OneHotEncoder().fit(X_cat2)
print(encoder2.categories_)

[array(['Disabled', 'Employed', 'Medical Leave', 'Retired', 'Unemployed'],
      dtype=object)]


In [60]:
X_cat2.head()

EmploymentStatus
0         Employed
1       Unemployed
2         Employed
3         Employed
4    Medical Leave

In [69]:
encoded1= encoder2.transform(X_cat2).toarray()
print (encoded1)

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [72]:
onehot_encoded1 = pd.DataFrame(encoded1,columns=encoder2.categories_)
onehot_encoded1.head()

Disabled Employed Medical Leave Retired Unemployed
0      0.0      1.0           0.0     0.0        0.0
1      0.0      0.0           0.0     0.0        1.0
2      0.0      1.0           0.0     0.0        0.0
3      0.0      1.0           0.0     0.0        0.0
4      0.0      0.0           1.0     0.0        0.0

In [75]:
X_cat3=categoricals.drop(['Customer', 'State', 'Coverage', 'EmploymentStatus', 'Gender', 'Location Code', 'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Vehicle Class', 'Vehicle Size'],axis=1) 
from sklearn.preprocessing import OneHotEncoder
encoder3 = OneHotEncoder().fit(X_cat3)
print(encoder3.categories_)

[array(['Bachelor', 'College', 'Doctor', 'High School or Below', 'Master'],
      dtype=object)]


In [76]:
X_cat3.head()

Education
0   College
1   College
2  Bachelor
3   College
4  Bachelor

In [79]:
encoded2= encoder3.transform(X_cat3).toarray()
print(encoded2)

[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [83]:
onehot_encoded2 = pd.DataFrame(encoded1,columns=encoder3.categories_)
onehot_encoded2.head()

Bachelor College Doctor High School or Below Master
0      0.0     1.0    0.0                  0.0    0.0
1      0.0     0.0    0.0                  0.0    1.0
2      0.0     1.0    0.0                  0.0    0.0
3      0.0     1.0    0.0                  0.0    0.0
4      0.0     0.0    1.0                  0.0    0.0

In [85]:
X_cat4=categoricals.drop(['Customer', 'State', 'Coverage', 'EmploymentStatus', 'Education', 'Location Code', 'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Vehicle Class', 'Vehicle Size'],axis=1) 
from sklearn.preprocessing import OneHotEncoder
encoder4 = OneHotEncoder().fit(X_cat4)
print(encoder4.categories_)

[array(['F', 'M'], dtype=object)]


In [86]:
X_cat4.head()

Gender
0      M
1      F
2      M
3      M
4      F

In [87]:
encoded3= encoder4.transform(X_cat4).toarray()
print(encoded3)

[[0. 1.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]


In [88]:
onehot_encoded3 = pd.DataFrame(encoded3,columns=encoder4.categories_)
onehot_encoded3.head()

F    M
0  0.0  1.0
1  1.0  0.0
2  0.0  1.0
3  0.0  1.0
4  1.0  0.0

In [ ]:
#Concat DataFrames

In [89]:
categorical_varables=pd.concat([onehot_encoded,onehot_encoded1,onehot_encoded2,onehot_encoded3],axis=0)

In [90]:
categorical_varables

Bachelor Basic College Disabled Doctor Employed Extended    F  \
0          NaN   1.0     NaN      NaN    NaN      NaN      0.0  NaN   
1          NaN   1.0     NaN      NaN    NaN      NaN      0.0  NaN   
2          NaN   1.0     NaN      NaN    NaN      NaN      0.0  NaN   
3          NaN   0.0     NaN      NaN    NaN      NaN      1.0  NaN   
4          NaN   0.0     NaN      NaN    NaN      NaN      0.0  NaN   
...        ...   ...     ...      ...    ...      ...      ...  ...   
10905      NaN   NaN     NaN      NaN    NaN      NaN      NaN  1.0   
10906      NaN   NaN     NaN      NaN    NaN      NaN      NaN  1.0   
10907      NaN   NaN     NaN      NaN    NaN      NaN      NaN  1.0   
10908      NaN   NaN     NaN      NaN    NaN      NaN      NaN  1.0   
10909      NaN   NaN     NaN      NaN    NaN      NaN      NaN  0.0   

      High School or Below    M Master Medical Leave Premium Retired  \
0                      NaN  NaN    NaN           NaN     0.0     NaN   
1                      NaN  NaN    NaN           NaN     0.0     NaN   
2                      NaN  NaN    NaN           NaN     0.0     NaN   
3                      NaN  NaN    NaN           NaN     0.0     NaN   
4                      NaN  NaN    NaN           NaN     1.0     NaN   
...                    ...  ...    ...           ...     ...     ...   
10905                  NaN  0.0    NaN           NaN     NaN     NaN   
10906                  NaN  0.0    NaN           NaN     NaN     NaN   
10907                  NaN  0.0    NaN           NaN     NaN     NaN   
10908                  NaN  0.0    NaN           NaN     NaN     NaN   
10909                  NaN  1.0    NaN           NaN     NaN     NaN   

      Unemployed  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
10905        NaN  
10906        NaN  
10907        NaN  
10908        NaN  
10909        NaN  

[43640 rows x 15 columns]

In [ ]:
#Train-test split

In [99]:
y = marketing_customer_analysis_cleaned_lab6['Total CLaim Amount']
X = marketing_customer_analysis_cleaned_lab6.drop(['Total CLaim Amount'], axis=1)


KeyError: 'Total CLaim Amount'

In [98]:
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = np.object)

NameError: name 'X' is not defined

In [92]:
from sklearn.preprocessing import MinMaxScaler
MinMaxtransformer = MinMaxScaler().fit(X_num)
x_normalized = MinMaxtransformer.transform(X_num)
print(x_normalized.shape)
x_normalized = pd.DataFrame(x_normalized,columns=X_num.columns)
x_normalized.head()

NameError: name 'X_num' is not defined

In [ ]:
#Apply linear regression

In [ ]:
# Model Validation R2 MSE RMSE MAE

In [100]:
from sklearn.metrics import mean_squared_error, r2_score

In [101]:
mse = mean_squared_error(y_test, predictions)
print(mse)

NameError: name 'y_test' is not defined

In [102]:
rmse = math.sqrt(mse)
print(rmse)

NameError: name 'math' is not defined

In [103]:
r2 = r2_score(y_test, predictions)
r2

NameError: name 'y_test' is not defined

In [104]:
marketing_customer_analysis_cleaned_lab6.to_csv('marketing_customer_analysis_cleaned_lab7.csv')